language: c

env:
  - PROJECT=get_next_line

script:
  - git clone https://github.com/yyang42/moulitest $HOME/moulitest
  - echo "GET_NEXT_LINE_PATH=$TRAVIS_BUILD_DIR" >> $HOME/moulitest/config.ini
  - cd $HOME/moulitest && make $PROJECT
